logging:
  level:
    root: INFO

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

server:
  address: 0.0.0.0
  port: 6446